### ISSUE TITLE
Possition of the $cell

### ISSUE THREAD

**Issue by fprijate** [intercellular/cell#14]
It would be nice if I could specify that $cell :

1.   replaces existing element
2.  is inserted as first child of existing element
3.  is inserted as a last child of existing element
4.  existing element is inserted into it as a first child.
5. existing element is inserted into it as a last child 

Maybe by extending $cell values:

```
var bla = {
   $cell: v,  
   $type:  "div",
   id: "div1",
   . . .
}
```
where v can be
```

  v=true      //   backward compatible
  v="R"       //    replaces div1 element
  v="CF"     //    is inserted as first child of div1 element
  v="CL"     //   is inserted as a last child of div1 element
  v="PF"     //   div1 element is inserted into it as a first child.
  v="PL"     //   div1 element is inserted into it as a last child 
``` 

It would be very useful when inserting some new content
into existing static html pages.

**Comment by gliechtenstein** [comment]
Thanks for the idea, I can definitely see where you're coming from.

If you're thinking about using cell with an existing DOM, I think you can easily achieve what you're looking for by using jQuery (via its appendTo, insertAfter, etc. methods) or even native DOM APIs like insertBefore, etc.) since Cell creates native HTML nodes. (If you're plugging Cell into an existing website, you're probably using jQuery anyway, and even if you're not using jQuery you can use vanilla javascript to move them around easily)

Since Cell's design goal is to be as minimal and abstract as possible, and since these features can be achieved with other means I don't think we need to implement this feature. I'll close this for now, but please feel free to reopen or leave a comment for further discussion. Thanks!

**Comment by fprijate** [comment]
Thanks for your answer

> Thanks for the idea, I can definitely see where you're coming from.

No. 
My primary intention is not to use cell as tool for minor modifications of existing HTML.
I have following in my mind.
Server sends me JSON and Cell renders it into existing DOM , which was previously rendered by cell.
In this case we should have factory method to do this.
Byproduct of this is also possibility of inserting cell's into existing static HTML.
Both insertions should be possible in previously discussed positions.

Also it would be nice if somebody (or group of us) make a converter from static HTML to cell's JSON.

**Comment by devsnek** [comment]
```js
const parse5 = require('parse5');

function node2cell(node) {
  const cell = {
    $type: node.nodeName.replace('#', ''),
    $components: [],
  };

  if (node.nodeName === '#text') cell.$text = node.value;
  if (node.attrs) for (const a of node.attrs) cell[a.name] = a.value;
  for (const child of node.childNodes || []) {
    if (child.nodeName === '#text') {
      if (!child.value.trim()) continue;
      if (node.childNodes.length === 1) cell.$text = child.value;
      else cell.$components.push(node2cell(child));
    } else {
      cell.$components.push(node2cell(child));
    }
  }
  if (!cell.$components.length) delete cell.$components;
  return cell;
}

module.exports = function convert(str) {
  const cell = parse5.parseFragment(str).childNodes.map(n => node2cell(n));
  cell.$cell = true;
  return cell;
}
```
