### ISSUE TITLE
Empty tag generate option

### ISSUE THREAD

**Issue by abeq** [intercellular/cell#32]
Current:
 $components: [{
    $type: "img",
    src: "http://localhost/img.jpg"
  },
-> <img src="http://localhost/img.jpg">

I want to generate empty tag with xml style (add '/' before '>').
->  <img src="http://localhost/img.jpg"/>

Could you add option to select it?

**Comment by codehz** [comment]
I think it is impossible to control the style...because it use `document.createElement` to create element(It means that the style is depended on browser's implement)

**Comment by gliechtenstein** [comment]
Currently there is no way to do so because like @codehz said, these elements are created natively by `document.createElement` and that's what browsers prefer.

I'm curious though, could you share why you want that format?

**Comment by abeq** [comment]
Thank you for your reply.
> I'm curious though, could you share why you want that format?
Because I want to use generated code with xml related processor such as xslt, etc.
Probably &lt;img src="foo/bar.png"&gt; will not be passed validation of xml parser.

**Comment by gliechtenstein** [comment]
Cell doesn't create HTML strings but actually creates HTML nodes on the browser. Therefore this is 100% dependent on how browser implements it (The recommended way nowadays is to NOT use the closing slashes for those nodes)

I don't know why you would want to pass an HTML through an XSLT parser, but if what you're looking for is to transform or compose nodes, you can do this BEFORE the nodes are created by Cell.

In fact this is the main strength of cell because it's powered by JSON. You can map, filter, sort, or run all kinds of functions on the original object before creating an HTML element.

There's not really much to be done about this so going to close for now.

But feel free to ask further questions, If the solution I suggested above was not what you were looking for I can try to suggest a solution for your problem. Anyway hope this answers your question!
